### ISSUE TITLE
The task memory field is still present after migration to v1.4

### ISSUE THREAD

**Issue by osukhoroslov** [wfcommons/makeflow-traces#1]
In v1.4 the `memory` field for task is replaced by the `memoryInBytes`. However it is still present in the instance files. I think it should be removed to avoid confusion.

Also I see the values of `sizeInBytes` for files are not changed after migration to v1.4. Please confirm whether the file sizes in v1.3 versions of Makeflow instances we actually in bytes? (similar to [this issue](https://github.com/wfcommons/pegasus-instances/issues/1) for Pegasus instances).

**Comment by osukhoroslov** [comment]
@rafaelfsilva please have a look

**Comment by henricasanova** [comment]
Although I didn't collect that data, I believe that yes, for Makeflow, the data sizes were in KB originally. The problem was only for Pegasus, which had wrong documentation about what units were used in its log file.

Regarding the newly generated instances I'll let Rafael reply (knowing that he's currently traveling).

**Comment by rafaelfsilva** [comment]
@osukhoroslov, Henri is correct in his answer regarding the unit.
I will investigate why some of the Makeflow instances did not get properly migrated.

**Comment by osukhoroslov** [comment]
Any update on this?

**Comment by osukhoroslov** [comment]
@rafaelfsilva did you get a chance to look into that issue?

**Comment by rafaelfsilva** [comment]
@osukhoroslov, sorry for the delay. I have updated the instances to remove the `memory` field

**Comment by osukhoroslov** [comment]
@rafaelfsilva Thanks for updating the instances. However I'm still confused about the `sizeInBytes` values. I see that during migration to 1.4 the values of `size` are just became the values of `sizeInBytes` for **both** Makeflow and Pegasus instances. However this contradicts the above reply from @henricasanova that "for Makeflow, the data sizes were in KB originally. The problem was only for Pegasus". According to this the size values should be multiplied to 1024 during the migration.

![изображение](https://github.com/wfcommons/makeflow-instances/assets/1322460/4278df16-41aa-4103-b4d4-3d7fe1887f59)

**Comment by rafaelfsilva** [comment]
@osukhoroslov, this repository will be archived. Instances using the new [WfFormat](https://github.com/wfcommons/WfFormat) are available in the new [WfInstances](https://github.com/wfcommons/WfInstances) repository.

Thank you!
